### ISSUE TITLE
parallel / concurrent execution

### ISSUE THREAD

**Issue by ghost** [dvopsway/sshmux#12]
I am not 100% sure since I never used pexcept before. However I have the feeling that the code is sequential and not concurrent/parallel. So it connect to `host a` first, executes a command and then connect to `host b` and executes a commend.

What we of course would like to see is that it connects to `host a` and `host b` at the same time and prints the output.

I am not sure about pexcept, but I can't find anything about concurrency or parallel execution in their documentation.

Maybe we can use something like [multiprocessing](https://docs.python.org/2.7/library/multiprocessing.html)?

Let me know what you think about it!

**Comment by dvopsway** [comment]
Implemented in https://github.com/dvopsway/sshmux/commit/a4a0041b4aeac282852989f82f2cad47850f24be
