### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by ghost** [dvopsway/sshmux#2]
Awesome work @dvopsway 

I forked the repo and am working on python3 support now!

🎉

**Comment by dvopsway** [comment]
@rjrhaverkamp Awesome, will be looking forward to the PR.

**Comment by ghost** [comment]
Thanks, I will try to keep it python2.7 compatible. I never worked with python2.7 but will see :)

**Comment by ghost** [comment]
hi @dvopsway 

I did a lot of work in #3 it still isn't python ready but I think the biggest parts are done now.
