### ISSUE TITLE
password authentication not working?

### ISSUE THREAD

**Issue by ghost** [dvopsway/sshmux#4]
Hi @dvopsway 

it is probably just me but I can't get it working to log in without an ssh key. 
Whatever I do I always get `Error: Invalid value for "--key" / "-k":  file doesn't exist` when I run something in the lines of `python ssh.py -u 'test' -i 127.0.0.1 --password 'test'`

Do you know a way to get this working?

Thanks!

**Comment by dvopsway** [comment]
Hi @rjrhaverkamp 

Got it , my bad this morning I was trying to put validation callback, looks like they made the variables mandatory, fixing it in my next commit.

**Comment by ghost** [comment]
Awesome! Thanks :)

**Comment by dvopsway** [comment]
@rjrhaverkamp This is fixed in https://github.com/dvopsway/sshmux/commit/e4e617f4db7f180ba33f6b3760ac6154502b5ffa

**Comment by ghost** [comment]
Awesome! Thanks!
