### ISSUE TITLE
hostname instead of IP

### ISSUE THREAD

**Issue by ghost** [dvopsway/sshmux#5]
At the moment it is only possible to use an IP address, I like the way on how the IP address gets validated before use.

I will work on something to be able to use hostnames and IP addresses.

Thanks for your work!

**Comment by dvopsway** [comment]
@rjrhaverkamp This was a simple addon, now supported after https://github.com/dvopsway/sshmux/commit/e4e617f4db7f180ba33f6b3760ac6154502b5ffa. Let me know if that works.

**Comment by ghost** [comment]
Hi @dvopsway 

Nice! It is indeed a simple addon, it tested it and it works.

You also fixed the password issue I believe?

Great work!
